apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: parser-restrict-egress
  namespace: teams-mattermost-migration
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: parser-job
  policyTypes:
    - Ingress
    - Egress
  egress:
    - to:
        - namespaceSelector: {}
      ports:
        - protocol: TCP
          port: 5432
        - protocol: TCP
          port: 6379
        - protocol: TCP
          port: 443
