apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: parser-data-pvc
  namespace: teams-mattermost-migration
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
