apiVersion: batch/v1
kind: Job
metadata:
  name: parser-job
  namespace: teams-mattermost-migration
spec:
  template:
    spec:
      containers:
        - name: parser
          image: teams-mattermost-parser@sha256:b1d8f8a846c4f826359df3ad871891b97ad89495fc9f63567761019623259
